import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { runGuidValidation } from "../src/tools/validateGuids.js";

const WORK = join(dirname(import.meta.filename), "_work-validate-guids");

const DUP_GUID_CLASS = "{E2125AB5-E5C4-4846-B78B-AB413DC9D2E2}";
const DUP_GUID_SERVER = "{CA5F3115-AD38-4327-A47E-8E9094D738A8}";

const CLASS_A_ST = `//This file was generated by the LASAL2 CodeGenerator
(*!
<Class
	Name               = "PrinterAlfaJetEvo"
	Revision           = "0.0"
	GUID               = "${DUP_GUID_CLASS}">
	<Channels>
		<Server Name="SPrinterOn" GUID="${DUP_GUID_SERVER}" Visualized="true" Initialize="true" DefValue="0" WriteProtected="false" Retentive="SRam"/>
	</Channels>
</Class>
*)
FUNCTION GLOBAL TAB PrinterAlfaJetEvo::@CT_
TO_UDINT(0), "PrinterAlfaJetEvo", //Class
TO_UDINT(0), 0, 0$UINT, 0$UINT, //Baseclass
(::PrinterAlfaJetEvo.SPrinterOn.pMeth)$UINT, _CH_SVR$UINT, 2#0000000000000000$UINT, TO_UDINT(0), "SPrinterOn",
END_FUNCTION
`;

const CLASS_B_ST = `//This file was generated by the LASAL2 CodeGenerator
(*!
<Class
	Name               = "PrinterSideWays"
	Revision           = "0.0"
	GUID               = "${DUP_GUID_CLASS}">
	<Channels>
		<Server Name="SPrinterOn" GUID="${DUP_GUID_SERVER}" Visualized="true" Initialize="true" DefValue="0" WriteProtected="false" Retentive="SRam"/>
	</Channels>
	<Network Name="Net1">
		<!-- List of temp data objects in this network -->
		<IOObjects>
			<IOObject KeyName="__IO_Element" Name="IO_Element" Position="(180,210)"/>
		</IOObjects>
	</Network>
</Class>
*)
FUNCTION GLOBAL TAB PrinterSideWays::@CT_
TO_UDINT(0), "PrinterSideWays", //Class
TO_UDINT(0), 0, 0$UINT, 0$UINT, //Baseclass
(::PrinterSideWays.SPrinterOn.pMeth)$UINT, _CH_SVR$UINT, 2#0000000000000000$UINT, TO_UDINT(0), "SPrinterOn",
END_FUNCTION
`;

const MAE_EXP_TXT = `[CRC]
12345678
"PrinterSideWays",${DUP_GUID_CLASS},
"PrinterSideWays","DINT","SPrinterOn",${DUP_GUID_SERVER},
`;

const MAE_EXP_XML = `<?xml version="1.0" encoding="utf-8" ?>
<File CRC="12345678">
	<Types>
		<Class Name="PrinterSideWays" Guid="${DUP_GUID_CLASS}">
			<Servers>
				<Server Name="SPrinterOn" Datatype="DINT" Guid="${DUP_GUID_SERVER}"/>
			</Servers>
		</Class>
	</Types>
</File>
`;

function setupProject(): { lcp: string } {
  rmSync(WORK, { recursive: true, force: true });
  mkdirSync(join(WORK, "Class", "PrinterAlfaJetEvo"), { recursive: true });
  mkdirSync(join(WORK, "Class", "PrinterSideWays"), { recursive: true });

  const lcp = join(WORK, "Station.lcp");
  writeFileSync(lcp, `<?xml version="1.0" ?><Project Name="Station"></Project>`, "latin1");

  writeFileSync(join(WORK, "Class", "PrinterAlfaJetEvo", "PrinterAlfaJetEvo.st"), CLASS_A_ST, "latin1");
  writeFileSync(join(WORK, "Class", "PrinterSideWays", "PrinterSideWays.st"), CLASS_B_ST, "latin1");
  writeFileSync(join(WORK, "MaeExp.txt"), MAE_EXP_TXT, "latin1");
  writeFileSync(join(WORK, "MaeExp.xml"), MAE_EXP_XML, "latin1");

  return { lcp };
}

beforeEach(() => {
  setupProject();
});

afterEach(() => {
  rmSync(WORK, { recursive: true, force: true });
});

describe("runGuidValidation", () => {
  it("detects duplicate GUIDs and auto-fixes collisions and @CT_ hashes", () => {
    const { lcp } = setupProject();
    const result = runGuidValidation(lcp, true);

    expect(result.ok).toBe(false);
    expect(result.collisions.length).toBe(2); // Class collision + Server collision
    expect(result.ctHashFixes.length).toBe(4); // 2 class hashes + 2 server hashes
    expect(result.cleanedMetadata.length).toBe(1); // Stripped <IOObjects>

    // Check Class A kept original GUID and updated @CT_ hashes
    const stA = readFileSync(join(WORK, "Class", "PrinterAlfaJetEvo", "PrinterAlfaJetEvo.st"), "latin1");
    expect(stA).toContain(`GUID               = "${DUP_GUID_CLASS}"`);
    expect(stA).not.toContain('TO_UDINT(0), "PrinterAlfaJetEvo"');
    expect(stA).not.toContain('TO_UDINT(0), "SPrinterOn"');
    expect(stA).toContain('TO_UDINT(4189548966), "PrinterAlfaJetEvo"');
    expect(stA).toContain('TO_UDINT(3638411201), "SPrinterOn"');

    // Check Class B got fresh unique GUIDs and updated @CT_ hashes
    const stB = readFileSync(join(WORK, "Class", "PrinterSideWays", "PrinterSideWays.st"), "latin1");
    expect(stB).not.toContain(`GUID               = "${DUP_GUID_CLASS}"`);
    expect(stB).not.toContain(`GUID="${DUP_GUID_SERVER}"`);
    expect(stB).not.toContain('TO_UDINT(0), "PrinterSideWays"');
    expect(stB).not.toContain('TO_UDINT(0), "SPrinterOn"');
    expect(stB).toContain('TO_UDINT(3638411201), "SPrinterOn"');
    expect(stB).not.toContain("<IOObjects>");

    // Check MaeExp files updated for Class B
    const maeTxt = readFileSync(join(WORK, "MaeExp.txt"), "latin1");
    expect(maeTxt).not.toContain(DUP_GUID_CLASS);
    expect(maeTxt).not.toContain(DUP_GUID_SERVER);

    const maeXml = readFileSync(join(WORK, "MaeExp.xml"), "latin1");
    expect(maeXml).not.toContain(DUP_GUID_CLASS);
    expect(maeXml).not.toContain(DUP_GUID_SERVER);

    // Second run should be completely clean and idempotent
    const second = runGuidValidation(lcp, true);
    expect(second.ok).toBe(true);
    expect(second.collisions).toHaveLength(0);
    expect(second.ctHashFixes).toHaveLength(0);
    expect(second.filesModified).toHaveLength(0);
  });
});
